// Generated by PicoPixel.io — https://picopixel.io
#ifndef PICOPIXEL_LVGL_UI_COLORS_H
#define PICOPIXEL_LVGL_UI_COLORS_H

#include <stdint.h>

#ifdef __cplusplus
extern "C" {
#endif

enum ThemesEnum {
    THEME_LIGHT,
    THEME_DARK,
    THEME_SUMMER,
};

enum ThemeColorsEnum {
    THEME_COLOR_TEXT,
};

extern const char *theme_names[3];
extern uint32_t theme_colors[3][1];
extern uint32_t active_theme_index;
void change_color_theme(uint32_t theme_index);

// Common colors
extern const uint32_t common_000000;
extern const uint32_t common_87ceeb;
extern const uint32_t common_cc0000;
extern const uint32_t common_d63939;
extern const uint32_t common_d67a28;
extern const uint32_t common_ffffff;

#ifdef __cplusplus
}
#endif

#endif /*PICOPIXEL_LVGL_UI_COLORS_H*/
