// Generated by PicoPixel.io — https://picopixel.io
#include "colors.h"

// Common colors
const uint32_t common_000000 = 0x000000;
const uint32_t common_87ceeb = 0x87ceeb;
const uint32_t common_cc0000 = 0xcc0000;
const uint32_t common_d63939 = 0xd63939;
const uint32_t common_d67a28 = 0xd67a28;
const uint32_t common_ffffff = 0xffffff;

