// Generated by PicoPixel.io — https://picopixel.io
#include "images.h"

#include "src/ui/images/day_partial_cloud.inc"
#include "src/ui/images/fog.inc"
#include "src/ui/images/alert.inc"
#include "src/ui/images/night_full_moon_clear.inc"
#include "src/ui/images/overcast.inc"
#include "src/ui/images/sleet.inc"
#include "src/ui/images/rain.inc"
#include "src/ui/images/day_clear.inc"
#include "src/ui/images/thunder.inc"
#include "src/ui/images/snow.inc"
#include "src/ui/images/night_full_moon_partial_cloud.inc"
const ext_img_desc_t images[11] = {
    { "day_partial_cloud", &day_partial_cloud },
    { "fog", &fog },
    { "alert", &alert },
    { "night_full_moon_clear", &night_full_moon_clear },
    { "overcast", &overcast },
    { "sleet", &sleet },
    { "rain", &rain },
    { "day_clear", &day_clear },
    { "thunder", &thunder },
    { "snow", &snow },
    { "night_full_moon_partial_cloud", &night_full_moon_partial_cloud }
};
