// Generated by PicoPixel.io — https://picopixel.io
#ifndef PICOPIXEL_LVGL_UI_IMAGES_H
#define PICOPIXEL_LVGL_UI_IMAGES_H

#include <lvgl.h>

#ifdef __cplusplus
extern "C" {
#endif


#ifndef EXT_IMG_DESC_T
#define EXT_IMG_DESC_T
typedef struct _ext_img_desc_t {
    const char *name;
    const lv_img_dsc_t *img_dsc;
} ext_img_desc_t;
#endif

extern const lv_img_dsc_t overcast;
extern const lv_img_dsc_t thunder;
extern const lv_img_dsc_t day_clear;
extern const lv_img_dsc_t snow;
extern const lv_img_dsc_t alert;
extern const lv_img_dsc_t rain;
extern const lv_img_dsc_t night_full_moon_clear;
extern const ext_img_desc_t images[7];


#ifdef __cplusplus
}
#endif

#endif /*PICOPIXEL_LVGL_UI_IMAGES_H*/
