// Generated by PicoPixel.io — https://picopixel.io
#ifndef PICOPIXEL_LVGL_UI_SCREENS_H
#define PICOPIXEL_LVGL_UI_SCREENS_H

#include <lvgl.h>

#ifdef __cplusplus
extern "C" {
#endif

typedef struct _objects_t {
    lv_obj_t *screenbiowetter2;
    lv_obj_t *screenbiowetter;
    lv_obj_t *screenairquality;
    lv_obj_t *screenmenu;
    lv_obj_t *screensunmoon;
    lv_obj_t *lagerscreen;
    lv_obj_t *screenwarnkarte2;
    lv_obj_t *screenwarnkarte1;
    lv_obj_t *screenforecastwetter;
    lv_obj_t *screenforecastpollenhour;
    lv_obj_t *screenforecastpollen;
    lv_obj_t *screenwarnung;
    lv_obj_t *screenwarnungpollen;
    lv_obj_t *screen_1;
    lv_obj_t *screenboot;
    lv_obj_t *labelwetter;
    lv_obj_t *labelcube;
    lv_obj_t *labelauthor;
    lv_obj_t *labelstatus;
    lv_obj_t *barwifi;
    lv_obj_t *labelpico;
    lv_obj_t *pico_dark_logo;
    lv_obj_t *labelbuttonbackward;
    lv_obj_t *labeltime;
    lv_obj_t *imagewetter;
    lv_obj_t *labeltemp;
    lv_obj_t *labeldatum;
    lv_obj_t *labelbuttonforward;
    lv_obj_t *labelpollenforecast1main;
    lv_obj_t *labelpollenforecast2main;
    lv_obj_t *labelpollenforecast3main;
    lv_obj_t *labelpollenforecasttext;
    lv_obj_t *labelpollenforecast1mainvalue;
    lv_obj_t *labelpollenforecast2mainvalue;
    lv_obj_t *labelpollenforecast3mainvalue;
    lv_obj_t *labelwinddirection;
    lv_obj_t *labelwindspeed;
    lv_obj_t *labelhumidity;
    lv_obj_t *labelairpressur;
    lv_obj_t *label_1;
    lv_obj_t *fc_settings;
    lv_obj_t *imagealert;
    lv_obj_t *labelpollenwarntitel;
    lv_obj_t *labelpollenwarnart;
    lv_obj_t *labelpollenwarnhint;
    lv_obj_t *imagewarnregen;
    lv_obj_t *labelwarntitel;
    lv_obj_t *labelwarndetail;
    lv_obj_t *labelwarndetail2;
    lv_obj_t *labelwarnhint;
    lv_obj_t *labelbuttonbackward_1;
    lv_obj_t *labelnamebirke;
    lv_obj_t *labelnamegraeser;
    lv_obj_t *labelnameerle;
    lv_obj_t *labelnamebeifuss;
    lv_obj_t *labelnameambrosia;
    lv_obj_t *labelnamehasel;
    lv_obj_t *labelnameesche;
    lv_obj_t *labelnameroggen;
    lv_obj_t *labelday1;
    lv_obj_t *labelday3;
    lv_obj_t *labelday2;
    lv_obj_t *labelbirkeday1;
    lv_obj_t *labelgraeserday1;
    lv_obj_t *labelerleday1;
    lv_obj_t *labelbeifussday1;
    lv_obj_t *labelambrosiaday1;
    lv_obj_t *labelhaselday1;
    lv_obj_t *labelescheday1;
    lv_obj_t *labelroggenday1;
    lv_obj_t *labelroggenday3;
    lv_obj_t *labelroggenday2;
    lv_obj_t *labelescheday3;
    lv_obj_t *labelescheday2;
    lv_obj_t *labelhaselday3;
    lv_obj_t *labelhaselday2;
    lv_obj_t *labelambrosiaday3;
    lv_obj_t *labelambrosiaday2;
    lv_obj_t *labelbeifussday2;
    lv_obj_t *labelbeifussday3;
    lv_obj_t *labelerleday2;
    lv_obj_t *labelerleday3;
    lv_obj_t *labelgraeserday2;
    lv_obj_t *labelgraeserday3;
    lv_obj_t *labelbirkeday2;
    lv_obj_t *labelbirkeday3;
    lv_obj_t *labelbuttonforward_1;
    lv_obj_t *labelbuttonhome;
    lv_obj_t *labelbuttonscreenhub;
    lv_obj_t *labelnamebirke_1;
    lv_obj_t *labelnamegraeser_1;
    lv_obj_t *labelnameerle_1;
    lv_obj_t *labelnamebeifuss_1;
    lv_obj_t *labelnameambrosia_1;
    lv_obj_t *labelnamehasel_1;
    lv_obj_t *labelnameesche_1;
    lv_obj_t *labelnameroggen_1;
    lv_obj_t *labelhour1;
    lv_obj_t *labelhour3;
    lv_obj_t *labelhour2;
    lv_obj_t *labelbirkehour1;
    lv_obj_t *labelgraeserhour1;
    lv_obj_t *labelerlehour1;
    lv_obj_t *labelbeifusshour1;
    lv_obj_t *labelambrosiahour1;
    lv_obj_t *labelhaselhour1;
    lv_obj_t *labeleschehour1;
    lv_obj_t *labelroggenhour1;
    lv_obj_t *labelroggenhour3;
    lv_obj_t *labelroggenhour2;
    lv_obj_t *labeleschehour3;
    lv_obj_t *labeleschehour2;
    lv_obj_t *labelhaselhour3;
    lv_obj_t *labelhaselhour2;
    lv_obj_t *labelambrosiahour3;
    lv_obj_t *labelambrosiahour2;
    lv_obj_t *labelbeifusshour2;
    lv_obj_t *labelbeifusshour3;
    lv_obj_t *labelerlehour2;
    lv_obj_t *labelerlehour3;
    lv_obj_t *labelgraeserhour2;
    lv_obj_t *labelgraeserhour3;
    lv_obj_t *labelbirkehour2;
    lv_obj_t *labelbirkehour3;
    lv_obj_t *labelbuttonhome_1;
    lv_obj_t *labelbuttonscreenhubback;
    lv_obj_t *labelbuttonhome_2;
    lv_obj_t *labelbuttonbackward_2;
    lv_obj_t *labelbuttonforward_2;
    lv_obj_t *labelh1zeit;
    lv_obj_t *labelh3zeit;
    lv_obj_t *labelh4zeit;
    lv_obj_t *labelh2zeit;
    lv_obj_t *imageh1;
    lv_obj_t *imageh2;
    lv_obj_t *imageh3;
    lv_obj_t *imageh4;
    lv_obj_t *labelh1temp;
    lv_obj_t *labelh2temp;
    lv_obj_t *labelh3temp;
    lv_obj_t *labelh4temp;
    lv_obj_t *labelh1winddirection;
    lv_obj_t *labelh2winddirection;
    lv_obj_t *labelh3winddirection;
    lv_obj_t *labelh4winddirection;
    lv_obj_t *labelh1windspeed;
    lv_obj_t *labelh2windspeed;
    lv_obj_t *labelh3windspeed;
    lv_obj_t *labelh4windspeed;
    lv_obj_t *labelbuttonbackward_3;
    lv_obj_t *labelbuttonforward_3;
    lv_obj_t *labelbuttonhome_3;
    lv_obj_t *labelbuttonscreenhub_1;
    lv_obj_t *labelbuttonhome_4;
    lv_obj_t *labelbuttonscreenhubback_1;
    lv_obj_t *image_1;
    lv_obj_t *fog;
    lv_obj_t *day_partial_cloud;
    lv_obj_t *snow;
    lv_obj_t *night_full_moon_partial_cloud;
    lv_obj_t *sleet;
    lv_obj_t *labeltempmaxvalue;
    lv_obj_t *labeltempmax;
    lv_obj_t *labeltempminvalue;
    lv_obj_t *labeltempmin;
    lv_obj_t *labelbuttonbackward_4;
    lv_obj_t *image_2;
    lv_obj_t *labelbuttonhome_5;
    lv_obj_t *labelbuttonforward_4;
    lv_obj_t *image_3;
    lv_obj_t *labeluvindex;
    lv_obj_t *labeluvindexvalue;
    lv_obj_t *labelsunrise;
    lv_obj_t *labelsundown;
    lv_obj_t *labelsunrisetime;
    lv_obj_t *labelsundowntime;
    lv_obj_t *labellightchange;
    lv_obj_t *labeldwdchange;
    lv_obj_t *labelbuttonmenu_2;
    lv_obj_t *labeltheme;
    lv_obj_t *labelregenchange;
    lv_obj_t *labelpollenchange;
    lv_obj_t *labelswitchtheme;
    lv_obj_t *regenswitch;
    lv_obj_t *pollenswitch;
    lv_obj_t *dwdswitch;
    lv_obj_t *labellightchangevalue;
    lv_obj_t *container_3;
    lv_obj_t *labelno2value;
    lv_obj_t *label_9;
    lv_obj_t *bar_3;
    lv_obj_t *label_9_1;
    lv_obj_t *container_2;
    lv_obj_t *labelpm10value;
    lv_obj_t *label_12;
    lv_obj_t *bar_2;
    lv_obj_t *label_12_1;
    lv_obj_t *labelbuttonforward_5;
    lv_obj_t *labelbuttonbackward_5;
    lv_obj_t *labelbuttonhome_6;
    lv_obj_t *arcaqi;
    lv_obj_t *labelaqivalue;
    lv_obj_t *label_3;
    lv_obj_t *label_4;
    lv_obj_t *labelaqistatus;
    lv_obj_t *container_1;
    lv_obj_t *labelpm25value;
    lv_obj_t *label_8;
    lv_obj_t *bar_1;
    lv_obj_t *label_10;
    lv_obj_t *container_4;
    lv_obj_t *labelo3value;
    lv_obj_t *label_11;
    lv_obj_t *bar_4;
    lv_obj_t *label_11_1;
    lv_obj_t *labelbuttonhome_7;
    lv_obj_t *labelbuttonbackward_4_1;
    lv_obj_t *labelbuttonscreenhub_2;
    lv_obj_t *labelbuttonforward_6;
    lv_obj_t *labelbioapsthmvm;
    lv_obj_t *labelbiow_rmevm;
    lv_obj_t *labelbiow_rmenm;
    lv_obj_t *labelbioapsthmam;
    lv_obj_t *labelbioreumdegenm;
    lv_obj_t *labelbioreumdegenvm;
    lv_obj_t *labelbioreumentznm;
    lv_obj_t *labelbiobpniedrigvm;
    lv_obj_t *labelbioreumentzvm;
    lv_obj_t *labelbiobpniedrignm;
    lv_obj_t *label_13;
    lv_obj_t *label_14;
    lv_obj_t *label_7;
    lv_obj_t *label_6;
    lv_obj_t *labelbiobphochnm;
    lv_obj_t *labelbiobphochvm;
    lv_obj_t *labelbiobewindennm;
    lv_obj_t *bluthochdruck;
    lv_obj_t *label_5;
    lv_obj_t *labelbiovmttg;
    lv_obj_t *labelbionmttg;
    lv_obj_t *label_2;
    lv_obj_t *labelbiobevindenvm;
    lv_obj_t *label_15;
    lv_obj_t *labelbuttonhome_8;
    lv_obj_t *labelbuttonscreenhubback_2;
    lv_obj_t *labelbioapsthmvm2;
    lv_obj_t *labelbiow_rmevm2;
    lv_obj_t *labelbiow_rmenm2;
    lv_obj_t *labelbioapsthmam2;
    lv_obj_t *labelbioreumdegenm2;
    lv_obj_t *labelbioreumdegenvm2;
    lv_obj_t *labelbioreumentznm2;
    lv_obj_t *labelbiobpniedrigvm2;
    lv_obj_t *labelbioreumentzvm2;
    lv_obj_t *labelbiobpniedrignm2;
    lv_obj_t *label_25;
    lv_obj_t *label_25_1;
    lv_obj_t *label_25_2;
    lv_obj_t *label_25_3;
    lv_obj_t *labelbiobphochnm2;
    lv_obj_t *labelbiobphochvm2;
    lv_obj_t *labelbiobewindennm2;
    lv_obj_t *label_25_4;
    lv_obj_t *label_25_5;
    lv_obj_t *labelbiomorgenvm;
    lv_obj_t *labelbiomorgennm;
    lv_obj_t *label_25_6;
    lv_obj_t *labelbiobevindenvm2;
    lv_obj_t *label_16;
    lv_obj_t *labelbuttonbackward_label;
    lv_obj_t *labelbuttonforward_label;
    lv_obj_t *labelbuttonbackward_1_label;
    lv_obj_t *labelbuttonforward_1_label;
    lv_obj_t *labelbuttonhome_label;
    lv_obj_t *labelbuttonscreenhub_label;
    lv_obj_t *labelbuttonhome_1_label;
    lv_obj_t *labelbuttonscreenhubback_label;
    lv_obj_t *labelbuttonhome_2_label;
    lv_obj_t *labelbuttonbackward_2_label;
    lv_obj_t *labelbuttonforward_2_label;
    lv_obj_t *labelbuttonbackward_3_label;
    lv_obj_t *labelbuttonforward_3_label;
    lv_obj_t *labelbuttonhome_3_label;
    lv_obj_t *labelbuttonscreenhub_1_label;
    lv_obj_t *labelbuttonhome_4_label;
    lv_obj_t *labelbuttonscreenhubback_1_label;
    lv_obj_t *labelbuttonbackward_4_label;
    lv_obj_t *labelbuttonhome_5_label;
    lv_obj_t *labelbuttonforward_4_label;
    lv_obj_t *labelbuttonmenu_2_label;
    lv_obj_t *labelswitchtheme_label;
    lv_obj_t *labelbuttonforward_5_label;
    lv_obj_t *labelbuttonbackward_5_label;
    lv_obj_t *labelbuttonhome_6_label;
    lv_obj_t *labelbuttonhome_7_label;
    lv_obj_t *labelbuttonbackward_4_1_label;
    lv_obj_t *labelbuttonscreenhub_2_label;
    lv_obj_t *labelbuttonforward_6_label;
    lv_obj_t *labelbuttonhome_8_label;
    lv_obj_t *labelbuttonscreenhubback_2_label;
} objects_t;

extern objects_t objects;

enum ScreensEnum {
    SCREEN_ID_SCREENBIOWETTER2 = 1,
    SCREEN_ID_SCREENBIOWETTER = 2,
    SCREEN_ID_SCREENAIRQUALITY = 3,
    SCREEN_ID_SCREENMENU = 4,
    SCREEN_ID_SCREENSUNMOON = 5,
    SCREEN_ID_LAGERSCREEN = 6,
    SCREEN_ID_SCREENWARNKARTE2 = 7,
    SCREEN_ID_SCREENWARNKARTE1 = 8,
    SCREEN_ID_SCREENFORECASTWETTER = 9,
    SCREEN_ID_SCREENFORECASTPOLLENHOUR = 10,
    SCREEN_ID_SCREENFORECASTPOLLEN = 11,
    SCREEN_ID_SCREENWARNUNG = 12,
    SCREEN_ID_SCREENWARNUNGPOLLEN = 13,
    SCREEN_ID_SCREEN_1 = 14,
    SCREEN_ID_SCREENBOOT = 15,
};

void create_screen_screenbiowetter2();
void tick_screen_screenbiowetter2();
void delete_screen_screenbiowetter2();
void create_screen_screenbiowetter();
void tick_screen_screenbiowetter();
void delete_screen_screenbiowetter();
void create_screen_screenairquality();
void tick_screen_screenairquality();
void delete_screen_screenairquality();
void create_screen_screenmenu();
void tick_screen_screenmenu();
void delete_screen_screenmenu();
void create_screen_screensunmoon();
void tick_screen_screensunmoon();
void delete_screen_screensunmoon();
void create_screen_lagerscreen();
void tick_screen_lagerscreen();
void delete_screen_lagerscreen();
void create_screen_screenwarnkarte2();
void tick_screen_screenwarnkarte2();
void delete_screen_screenwarnkarte2();
void create_screen_screenwarnkarte1();
void tick_screen_screenwarnkarte1();
void delete_screen_screenwarnkarte1();
void create_screen_screenforecastwetter();
void tick_screen_screenforecastwetter();
void delete_screen_screenforecastwetter();
void create_screen_screenforecastpollenhour();
void tick_screen_screenforecastpollenhour();
void delete_screen_screenforecastpollenhour();
void create_screen_screenforecastpollen();
void tick_screen_screenforecastpollen();
void delete_screen_screenforecastpollen();
void create_screen_screenwarnung();
void tick_screen_screenwarnung();
void delete_screen_screenwarnung();
void create_screen_screenwarnungpollen();
void tick_screen_screenwarnungpollen();
void delete_screen_screenwarnungpollen();
void create_screen_screen_1();
void tick_screen_screen_1();
void delete_screen_screen_1();
void create_screen_screenboot();
void tick_screen_screenboot();
void delete_screen_screenboot();

void tick_screen_by_id(enum ScreensEnum screenId);
void tick_screen(int screen_index);

void delete_screen_by_id(enum ScreensEnum screenId);

void create_screens();


#ifdef __cplusplus
}
#endif

#endif /*PICOPIXEL_LVGL_UI_SCREENS_H*/
