// Generated by PicoPixel.io — https://picopixel.io
/**
 * @file fonts.c
 * @brief Custom font lookup for LVGL UI
 *
 * Each font .c file is compiled separately.
 */

#include "fonts.h"
#include <string.h>

const lv_font_t* ui_get_font_by_name(const char* name) {
    if (name == NULL) return NULL;
    if (strcmp(name, "font_17e6ca586d88805280082a7bfe21eea3") == 0) return &font_17e6ca586d88805280082a7bfe21eea3;
    if (strcmp(name, "font_17e6ca586d88805280082a7bfe21eea4") == 0) return &font_17e6ca586d88805280082a7bfe21eea4;
    if (strcmp(name, "font_17e6ca586d88805280082a7bfe21eea5") == 0) return &font_17e6ca586d88805280082a7bfe21eea5;
    if (strcmp(name, "font_17e6ca586d88805280082a7bfe21eea6") == 0) return &font_17e6ca586d88805280082a7bfe21eea6;
    if (strcmp(name, "font_17e6ca586d88805280082a7bfe21eea7") == 0) return &font_17e6ca586d88805280082a7bfe21eea7;
    if (strcmp(name, "font_dbb05fdd34e280e180082b1d61d53d7d") == 0) return &font_dbb05fdd34e280e180082b1d61d53d7d;
    return NULL;
}
