// Generated by PicoPixel.io — https://picopixel.io
#ifndef PICOPIXEL_LVGL_UI_SCREENS_H
#define PICOPIXEL_LVGL_UI_SCREENS_H

#include <lvgl.h>

#ifdef __cplusplus
extern "C" {
#endif

typedef struct _objects_t {
    lv_obj_t *screen_1;
    lv_obj_t *screenboot;
    lv_obj_t *labelstatus;
    lv_obj_t *labelcube;
    lv_obj_t *barwifi;
    lv_obj_t *labelauthor;
    lv_obj_t *labeltime;
    lv_obj_t *labelwetter;
} objects_t;

extern objects_t objects;

enum ScreensEnum {
    SCREEN_ID_SCREEN_1 = 1,
    SCREEN_ID_SCREENBOOT = 2,
};

void create_screen_screen_1();
void tick_screen_screen_1();
void delete_screen_screen_1();
void create_screen_screenboot();
void tick_screen_screenboot();
void delete_screen_screenboot();

void tick_screen_by_id(enum ScreensEnum screenId);
void tick_screen(int screen_index);

void delete_screen_by_id(enum ScreensEnum screenId);

void create_screens();


#ifdef __cplusplus
}
#endif

#endif /*PICOPIXEL_LVGL_UI_SCREENS_H*/
