// Generated by PicoPixel.io — https://picopixel.io
#include <string.h>

#include "screens.h"
#include "images.h"
#include "fonts/fonts.h"
#include "actions.h"
#include "vars.h"
#include "styles.h"
#include "ui.h"

objects_t objects;
lv_obj_t *tick_value_change_obj;
uint32_t active_theme_index = 0;

void create_screen_screen_1() {
    lv_obj_t *obj = lv_obj_create(0);
    objects.screen_1 = obj;
    lv_obj_set_pos(obj, 0, 0);
    lv_obj_set_size(obj, 480, 320);
    {
        lv_obj_t *parent_obj = obj;
        {
            // labeltime
            lv_obj_t *obj = lv_label_create(parent_obj);
            objects.labeltime = obj;
            lv_obj_set_pos(obj, 202, 40);
            lv_obj_set_size(obj, LV_SIZE_CONTENT, LV_SIZE_CONTENT);
            lv_obj_set_style_text_font(obj, &font_17e6ca586d88805280082a7bfe21eea6, LV_PART_MAIN | LV_STATE_DEFAULT);
            lv_label_set_text(obj, "12:45");
        }
    }

    tick_screen_screen_1();
}

void tick_screen_screen_1() {
}


void create_screen_screenboot() {
    lv_obj_t *obj = lv_obj_create(0);
    objects.screenboot = obj;
    lv_obj_set_pos(obj, 0, 0);
    lv_obj_set_size(obj, 480, 320);
    {
        lv_obj_t *parent_obj = obj;
        {
            // labelstatus
            lv_obj_t *obj = lv_label_create(parent_obj);
            objects.labelstatus = obj;
            lv_obj_set_pos(obj, 153, 177);
            lv_obj_set_size(obj, LV_SIZE_CONTENT, LV_SIZE_CONTENT);
            lv_obj_set_style_text_font(obj, &font_17e6ca586d88805280082a7bfe21eea4, LV_PART_MAIN | LV_STATE_DEFAULT);
            lv_label_set_text(obj, "Verbinde mit WLAN...");
        }
        {
            // labelcube
            lv_obj_t *obj = lv_label_create(parent_obj);
            objects.labelcube = obj;
            lv_obj_set_pos(obj, 214, 44);
            lv_obj_set_size(obj, LV_SIZE_CONTENT, LV_SIZE_CONTENT);
            lv_obj_set_style_text_opa(obj, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
            lv_obj_set_style_text_font(obj, &font_17e6ca586d88805280082a7bfe21eea7, LV_PART_MAIN | LV_STATE_DEFAULT);
            lv_obj_set_style_text_color(obj, lv_color_hex(0xff87ceeb), LV_PART_MAIN | LV_STATE_DEFAULT);
            lv_label_set_text(obj, "CubePlus");
        }
        {
            // barwifi
            lv_obj_t *obj = lv_bar_create(parent_obj);
            objects.barwifi = obj;
            lv_obj_set_pos(obj, 138, 230);
            lv_obj_set_size(obj, 200, 20);
            lv_bar_set_range(obj, 0, 100);
            lv_bar_set_mode(obj, LV_BAR_MODE_RANGE);
            lv_bar_set_start_value(obj, 0, LV_ANIM_OFF);
            lv_bar_set_value(obj, 50, LV_ANIM_OFF);
        }
        {
            // labelauthor
            lv_obj_t *obj = lv_label_create(parent_obj);
            objects.labelauthor = obj;
            lv_obj_set_pos(obj, 159, 125);
            lv_obj_set_size(obj, LV_SIZE_CONTENT, LV_SIZE_CONTENT);
            lv_obj_set_style_text_font(obj, &font_17e6ca586d88805280082a7bfe21eea5, LV_PART_MAIN | LV_STATE_DEFAULT);
            lv_label_set_text(obj, "by Jan Althaus");
        }
        {
            // labelwetter
            lv_obj_t *obj = lv_label_create(parent_obj);
            objects.labelwetter = obj;
            lv_obj_set_pos(obj, 46, 44);
            lv_obj_set_size(obj, LV_SIZE_CONTENT, LV_SIZE_CONTENT);
            lv_obj_set_style_text_font(obj, &font_17e6ca586d88805280082a7bfe21eea7, LV_PART_MAIN | LV_STATE_DEFAULT);
            lv_label_set_text(obj, "Wetter");
        }
    }

    tick_screen_screenboot();
}

void tick_screen_screenboot() {
}



typedef void (*tick_screen_func_t)();
tick_screen_func_t tick_screen_funcs[] = {
    tick_screen_screen_1,
    tick_screen_screenboot,
};
void tick_screen(int screen_index) {
    tick_screen_funcs[screen_index]();
}
void tick_screen_by_id(enum ScreensEnum screenId) {
    tick_screen_funcs[screenId - 1]();
}

void delete_screen_screen_1() {
    if (objects.screen_1 != NULL) {
        pp_anim_stop_timelines_for_deleted_tree(objects.screen_1);
        lv_obj_del(objects.screen_1);
    }
    objects.screen_1 = 0;
    objects.labeltime = 0;
}

void delete_screen_screenboot() {
    if (objects.screenboot != NULL) {
        pp_anim_stop_timelines_for_deleted_tree(objects.screenboot);
        lv_obj_del(objects.screenboot);
    }
    objects.screenboot = 0;
    objects.labelstatus = 0;
    objects.labelcube = 0;
    objects.barwifi = 0;
    objects.labelauthor = 0;
    objects.labelwetter = 0;
}


typedef void (*delete_screen_func_t)();
delete_screen_func_t delete_screen_funcs[] = {
    delete_screen_screen_1,
    delete_screen_screenboot,
};
void delete_screen_by_id(enum ScreensEnum screenId) {
    delete_screen_funcs[screenId - 1]();
}

void create_screens() {
    lv_disp_t *dispp = lv_disp_get_default();
    // Use dark theme (true) to match the editor's appearance - white text on dark buttons
    lv_theme_t *theme = lv_theme_default_init(dispp, lv_palette_main(LV_PALETTE_BLUE), lv_palette_main(LV_PALETTE_RED), true, LV_FONT_DEFAULT);
    lv_disp_set_theme(dispp, theme);

    create_screen_screen_1();
    create_screen_screenboot();
}
